### PR TITLE
Fix Leow9-w instructions (and provide new firmware)

### PR DESCRIPTION
**Pull request by brs17**
The instructions that were here were for the leow9/leow9-b but those instructions do not work on the leow9-w. This pr should fix that. This pr also includes updated firmware.rom and fpt.efi for updating to the latest firmware we have (that has yet another security patch).

@jackpot51 Could you confirm this all looks good and that the instructions are correct?
@ahoneybun Could you confirm that the instructions are understandable and clear?

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by jackpot51** [comment]
It looks correct to me

**Comment by ahoneybun** [comment]
2. Put the firmware.rom and fpt.efi files on a MBR formatted FAT partitioned drive.

We should have some instructions for taking off the side panel or a photo highlighting the screws. Also that the glass panel will need to be held so it does not drop and break.

Between 6-7 there is no command to list the devices unless that has changed recently.

**Comment by brs17** [comment]
@ahoneybun I made changes per your suggestions (Thank you!). How does it look now?

**Review by ahoneybun — COMMENTED** [review]
Just need to fix the *pannel* typo.

**Comment by brs17** [comment]
I think I got them all @ahoneybun !

**Comment by brs17** [comment]
Let's merge this @jackpot51 !

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
