### PR TITLE
Remove Firmware instructions on Meer3

### PR DESCRIPTION
**Pull request by Socialhappiness**
Support has created a copy of the document and will provide to customers upon request. This information needs removed from the guides page.

### CODE REVIEW

**Comment by WatchMkr** [comment]
This will break links here which should be preserved: https://system76.com/security/sa-00086

How is this done for the Wild Dog?

**Comment by Socialhappiness** [comment]
I have no idea, we just need it removed. That link links to the security page which links back to the guide page, so it's just circles. We have it saved in a doc. We keep getting complaints about customers flashing their firmware right when they receive their system.

**Comment by WatchMkr** [comment]
Okay, we can come up with a better solution. Come back to my office.

**Comment by jackpot51** [comment]
As discussed in Slack, we will address this with https://github.com/pop-os/system76-driver/issues/62

**Pull request closed without merging**
